Hw02 express
valery-chumak/nodejs-homework-rest-api pull request #1
Opened 2022-12-06 21:14 UTC by valery-chumak

Домашня робота 2. Перевірте будь ласка)

2022-12-07 08:44 UTC, BohdanGres requested changes
все чудово, давай винесемо валідацію в мідлварку + ствриш ще мадлвар для перевірки req.params що б бути впевненим що contactId приходить такий як треба

2022-12-07 08:44 UTC, BohdanGres commented on routes/api/contacts.js
> +const ctrl = require("../../controllers/contacts");
краще назвати сontactСontroller така назва одразу дасть зрозуміти що це таке

2022-12-07 14:50 UTC, valery-chumak commented on routes/api/contacts.js
> +const ctrl = require("../../controllers/contacts");
Перейменувала контроллер та додала валідацію на id в schemes. Я думала, що ці schemes і є мідлвар чи я помиляюся?

2022-12-07 18:13 UTC, BohdanGres requested changes

2022-12-07 18:13 UTC, BohdanGres commented on routes/api/contacts.js
> +
мідлвар буде підключатись от тут, за допомогою нього в тебе вийде ланцюг опрацювання запиту, спочатку він попаде в мідлвар в якому провалідує вхідні параметри а далі попаде в твій контролер в якому вже виконає якусь логіку
от непогані приклади https://developer.okta.com/blog/2018/09/13/build-and-understand-express-middleware-through-examples

2022-12-08 09:50 UTC, BohdanGres approved these changes

2022-12-08 13:30 UTC, valery-chumak commented on routes/api/contacts.js
> +
Додала мідлвар validationContacts сподіваюся на цей раз правильно)

2022-12-08 20:07 UTC, merged