Hw04 auth
valery-chumak/nodejs-homework-rest-api pull request #3
Opened 2022-12-29 14:25 UTC by valery-chumak

Перевірте будь ласка 4 дз.

2022-12-30 09:35 UTC, BohdanGres requested changes
все добре, декілька зауважень

2022-12-30 09:35 UTC, BohdanGres commented on app.js
>  app.use("/api/contacts", contactsRouter);
можна спробувати навісити мідлвар авторизації одрузу тут на весь роут /api/contacts, перевір чи помилки нормально обробляються

2022-12-30 09:35 UTC, BohdanGres commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
забула перевірити чи user.token === token

2023-01-01 15:16 UTC, valery-chumak commented on app.js
>  app.use("/api/contacts", contactsRouter);
Навісила мідлвар на весь роут, наче все працює добре. Дякую за підказку

2023-01-01 15:16 UTC, valery-chumak commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
Додала)

2023-01-02 13:55 UTC, BohdanGres approved these changes

2023-01-06 14:30 UTC, merged